sudo: required
services:
  - docker

language: ruby

rvm:
  - "2.4.1"

install:
  - docker-compose -f ./.travis/docker-compose-travis.yml build test-forum

script:
  - docker-compose -f ./.travis/docker-compose-travis.yml run --rm test-forum
